[config]
model="bedrock/anthropic.claude-3-haiku-20240307-v1:0"
model_turbo="bedrock/anthropic.claude-3-haiku-20240307-v1:0"
fallback_models=["bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0"]

[pr_reviewer]
num_code_suggestions=5
inline_code_comments=true
extra_instructions="answer in Japanese"
