[config]
model="bedrock/anthropic.claude-3-haiku-20240307-v1:0"
model_turbo="bedrock/anthropic.claude-3-haiku-20240307-v1:0"
fallback_models=["bedrock/anthropic.claude-3-haiku-20240307-v1:0"]

[pr_reviewer]
num_code_suggestions=5
inline_code_comments=true
extra_instructions="""
You must always answer in Japanese.
必ず日本語で回答してください。
"""

[pr_description]
extra_instructions="""
You must always answer in Japanese.
必ず日本語で回答してください。
"""

[pr_questions]
extra_instructions="""
You must always answer in Japanese.
必ず日本語で回答してください。
"""

[pr_code_suggestions]
extra_instructions="""
You must always answer in Japanese.
必ず日本語で回答してください。
"""

[pr_update_changelog]
extra_instructions="""
You must always answer in Japanese.
必ず日本語で回答してください。
"""

[litellm]
drop_params = true