name: CDKのdiffを出力します

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  diff:
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::151671725617:role/github-ftft
    - run: |
        npm install
        npm install -g aws-cdk

    - name: CDKの差分を出力します
      run: cdk diff
      env:
        AWS_DEFAULT_REGION: ap-northeast-1
