name: CDKをデプロイします

on:
  push:
    branches:
      - main

concurrency:
  group: cdk-deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./iac
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ap-northeast-1
        role-to-assume: arn:aws:iam::151671725617:role/github-ftft
    - run: |
        npm install
        npm install -g aws-cdk
    - run: cd ../frontend && corepack enable pnpm && pnpm i && pnpm build
    - run: cd ../backend && ./build.sh
    - name: Deploy to AWS
      run: cdk deploy --require-approval never --all
      env:
        AWS_DEFAULT_REGION: ap-northeast-1
        LINE_CHANNEL_SECRET: ${{ secrets.LINE_CHANNEL_SECRET }}
        LINE_CHANNEL_SECRET_FOR_MESSAGING: ${{ secrets.LINE_CHANNEL_SECRET_FOR_MESSAGING }}
        API_KEY: ${{ secrets.API_KEY }}
