on:
  issue_comment:
    types: [created]
jobs:
  pr_agent_job:
    # botではない&PRのコメントのみ
    if: ${{ github.event.sender.type != 'Bot' && github.event.issue.pull_request }}
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
      id-token: write
    name: Run pr agent on every pull request, respond to user comments
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::151671725617:role/github-ftft
      - run: echo $GITHUB_WORKSPACE/.pr_agent.toml
      - run: pwd
      - run: echo $PWD/.pr_agent.toml
      - run: echo "${{ vars.PR_AGENT_CONFIG_FILE }}" > $GITHUB_WORKSPACE/.pr_agent.toml
      - run: cat $GITHUB_WORKSPACE/.pr_agent.toml
      - run: echo "${{ vars.PR_AGENT_CONFIG_FILE }}" | sed 's/\\n/\n/g' > output.txt
      - run: cat output.txt
      - run: cat << EOS ${{ vars.PR_AGENT_CONFIG_FILE }} EOS > hoge2.txt
      - run: cat hoge2.txt
      - run: echo ${{ vars.PR_AGENT_CONFIG_FILE }} > $GITHUB_WORKSPACE/huga.toml
      - run: cat $GITHUB_WORKSPACE/huga.toml
      # - name: PR Agent action step
      #   id: pragent
      #   uses: Codium-ai/pr-agent@main
      #   env:
      #     OPENAI_KEY: dummy
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
